export const FETCH_GET_AMIIBO = 'FETCH_GET_AMIIBO'
export const FETCH_GET_AMIIBO_SUCCESS = 'FETCH_GET_AMIIBO_SUCCESS'
export const FETCH_GET_AMIIBO_FAILURE = 'FETCH_GET_AMIIBO_FAILURE'
export const FETCH_GET_AMIIBO_CANCEL = 'FETCH_GET_AMIIBO_CANCEL'
